#!/usr/bin/env bash
# Copyright (c) 2023 Nida Tech AB. All rights reserved.

# Exit on any error
set -o errexit
set -o pipefail
set -o nounset

SCRIPT_DIR=$(dirname "$(realpath -s "$0")")
ROOT_DIR=${SCRIPT_DIR}/..
PREFIX="${HOME}/.local"

pushd ${ROOT_DIR}
PATH="$PATH:${PREFIX}/bin" buf generate . --exclude-path java --exclude-path example-workspace --exclude-path tests --verbose --debug
popd

# Check if code generated has diffs, fail if any diff is found
DIFF_FOUND=0
[[ -n $(git status --short "${ROOT_DIR}/validate") ]] && DIFF_FOUND=1
if [ $DIFF_FOUND -ne 0 ]; then
    echo -e "\033[0;31mWARNING! Diff found in autogenerated code. Please commit these changes.\033[0m"
    exit 1
fi
